'use client';

import { useMemo, useState } from 'react';
import { Icon, type IconName } from '../../ui/icons';
import { useMarketing } from '../marketing-context';
import { MarketingPageHero } from '../marketing-page-components';

const docs: Array<{ icon: IconName; category: string; ar: string; en: string; arText: string; enText: string }> = [
  { icon: 'rocket', category: 'start', ar: 'البدء السريع', en: 'Quick start', arText: 'شغّل الخدمات وسجّل الدخول وافتح لوحة المدير لأول مرة.', enText: 'Run services, sign in, and open the manager dashboard for the first time.' },
  { icon: 'dashboard', category: 'manager', ar: 'دليل لوحة المدير', en: 'Manager dashboard guide', arText: 'افهم المؤشرات والرسوم والتنبيهات وتسلسل النشاط.', enText: 'Understand metrics, charts, alerts, and the activity timeline.' },
  { icon: 'monitor', category: 'agent', ar: 'دليل وكيل Windows', en: 'Windows agent guide', arText: 'الجلسات وحالة الاتصال والمزامنة والمهام الشخصية.', enText: 'Sessions, connection status, synchronization, and personal tasks.' },
  { icon: 'performance', category: 'analytics', ar: 'فهم التحليلات', en: 'Understanding analytics', arText: 'تعريف الإنتاجية والتركيز والخمول والتوزيع الزمني.', enText: 'Definitions for productivity, focus, idle time, and time distribution.' },
  { icon: 'shield', category: 'privacy', ar: 'الخصوصية وجمع البيانات', en: 'Privacy and data collection', arText: 'ما يتم جمعه وما لا يتم جمعه وكيف تُحمى البيانات.', enText: 'What is collected, what is not, and how data is protected.' },
  { icon: 'cloud', category: 'sync', ar: 'المزامنة دون اتصال', en: 'Offline synchronization', arText: 'كيف يعمل الطابور المحلي وإعادة المحاولة التلقائية.', enText: 'How the local queue and automatic retry work.' },
  { icon: 'tasks', category: 'tasks', ar: 'المهام وسير العمل', en: 'Tasks and workflow', arText: 'الإسناد والحالات والتقدم وربط المهام بالأداء.', enText: 'Assignment, status, progress, and performance context.' },
  { icon: 'code', category: 'api', ar: 'حدود REST API', en: 'REST API boundaries', arText: 'مرجع مستقبلي لتكاملات موثقة وآمنة.', enText: 'A future reference for documented, secure integrations.' },
];

export default function DocumentationPage() {
  const { ar } = useMarketing();
  const [query, setQuery] = useState('');
  const filtered = useMemo(() => docs.filter(item => `${item.ar} ${item.en} ${item.arText} ${item.enText}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <><MarketingPageHero eyebrow="DOCUMENTATION" titleAr="مركز معرفة جاهز لينمو مع المنتج" titleEn="A knowledge center ready to grow with the product" textAr="نقطة البداية لشرح لوحة المدير ووكيل Windows والتحليلات والخصوصية. المحتوى الحالي يعرّف المسارات، وستضاف الأدلة التفصيلية مع كل إصدار." textEn="The starting point for manager, Windows agent, analytics, and privacy guidance. Current content defines the paths, with detailed guides expanding alongside each release." actions={false}/>
    <section className="marketing-section compact"><div className="marketing-container docs-layout"><aside className="docs-sidebar"><strong>{ar ? 'الأقسام' : 'SECTIONS'}</strong><a href="#guides">{ar ? 'الأدلة' : 'Guides'}</a><a href="#quickstart">{ar ? 'البدء السريع' : 'Quick start'}</a><a href="#architecture">{ar ? 'حدود النظام' : 'System boundaries'}</a><a href="/privacy">{ar ? 'الخصوصية' : 'Privacy'}</a><a href="/contact">{ar ? 'طلب مساعدة' : 'Get help'}</a></aside><div className="docs-content"><label className="docs-search"><Icon name="search" size={16}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder={ar ? 'ابحث في موضوعات التوثيق…' : 'Search documentation topics…'} aria-label={ar ? 'بحث التوثيق' : 'Search documentation'}/></label><div id="guides" className="docs-grid">{filtered.map(item => <a className="doc-card" href={`#${item.category}`} key={item.category}><span><Icon name={item.icon}/></span><div><strong>{ar ? item.ar : item.en}</strong><small>{ar ? item.arText : item.enText}</small></div><Icon name="arrow" size={13}/></a>)}</div>{!filtered.length && <div className="quickstart"><h2>{ar ? 'لا توجد نتيجة مطابقة' : 'No matching topic'}</h2><p>{ar ? 'جرّب كلمة مثل المزامنة أو التحليلات أو الخصوصية.' : 'Try a term such as synchronization, analytics, or privacy.'}</p></div>}
        <article id="quickstart" className="quickstart"><h2>{ar ? 'البدء السريع' : 'Quick start'}</h2><p>{ar ? 'المسار الأساسي من تشغيل النظام إلى أول جلسة عمل.' : 'The essential path from running the system to the first work session.'}</p><div className="quickstart-steps"><article><span>01</span><div><strong>{ar ? 'شغّل الخدمات المحلية' : 'Run local services'}</strong><p>{ar ? 'شغّل قاعدة البيانات وBackend وتطبيق الويب حسب دليل التشغيل في المشروع.' : 'Start the database, backend, and web application using the project operations guide.'}</p></div></article><article><span>02</span><div><strong>{ar ? 'ادخل إلى لوحة المدير' : 'Enter the manager dashboard'}</strong><p>{ar ? 'افتح الموقع العام، اختر تسجيل الدخول، ثم استخدم حساب الإدارة المصرح.' : 'Open the public site, choose Sign in, and use an authorized manager account.'}</p></div></article><article><span>03</span><div><strong>{ar ? 'شغّل وكيل الموظف' : 'Start the employee agent'}</strong><p>{ar ? 'سجّل الدخول في تطبيق Windows، راجع حالة الاتصال، ثم ابدأ جلسة العمل.' : 'Sign into the Windows application, review connection status, and start a work session.'}</p></div></article><article><span>04</span><div><strong>{ar ? 'تحقق من المزامنة والتحليل' : 'Verify synchronization and analytics'}</strong><p>{ar ? 'راجع ملف الموظف ولوحة الأداء للتأكد من وصول الجلسة والنشاط واللقطات.' : 'Review the employee profile and performance workspace to confirm session, activity, and screenshots arrived.'}</p></div></article></div></article>
        <article id="architecture" className="quickstart"><h2>{ar ? 'حدود النظام الثابتة' : 'Fixed system boundaries'}</h2><p>{ar ? 'هذه الحدود أساسية لفهم تشغيل المنتج وتوسيعه بأمان.' : 'These boundaries are essential for operating and extending the product safely.'}</p><div className="quickstart-steps"><article><span><Icon name="globe" size={14}/></span><div><strong>{ar ? 'المدير: تطبيق ويب فقط' : 'Manager: web application only'}</strong><p>{ar ? 'لا يجمع المتصفح نشاط سطح المكتب.' : 'The browser does not collect desktop activity.'}</p></div></article><article><span><Icon name="monitor" size={14}/></span><div><strong>{ar ? 'الموظف: وكيل Windows فقط' : 'Employee: Windows agent only'}</strong><p>{ar ? 'الوكيل مسؤول عن الجمع المحلي وحالة الجلسة.' : 'The agent owns local collection and session state.'}</p></div></article><article><span><Icon name="code" size={14}/></span><div><strong>{ar ? 'التواصل: REST آمن فقط' : 'Communication: secure REST only'}</strong><p>{ar ? 'لا يصل أي مكون إلى كود أو قاعدة بيانات مكون آخر.' : 'No component accesses another component’s code or database.'}</p></div></article></div></article></div></div></section></>;
}
