'use client';

import Link from 'next/link';
import { Icon, type IconName } from '../../ui/icons';
import { useMarketing } from '../marketing-context';
import { FinalCta, MarketingPageHero } from '../marketing-page-components';
import { AgentPreview, DashboardPreview, FeatureIllustration } from '../marketing-visuals';

const indexItems: Array<{ id: string; icon: IconName; ar: string; en: string; arSmall: string; enSmall: string }> = [
  { id: 'analytics', icon: 'performance', ar: 'تحليلات الإنتاجية', en: 'Productivity analytics', arSmall: 'اتجاهات ومقارنات', enSmall: 'Trends and comparisons' },
  { id: 'activity', icon: 'activity', ar: 'نشاط العمل', en: 'Work activity', arSmall: 'تطبيقات ومواقع وخمول', enSmall: 'Apps, sites, and idle time' },
  { id: 'tasks', icon: 'tasks', ar: 'إدارة المهام', en: 'Task management', arSmall: 'تقدم وسياق إنجاز', enSmall: 'Progress and delivery context' },
  { id: 'screenshots', icon: 'monitor', ar: 'لقطات الشاشة', en: 'Screenshots', arSmall: 'ضغط ومنع تكرار', enSmall: 'Compression and deduplication' },
  { id: 'ai', icon: 'sparkles', ar: 'الرؤى الذكية', en: 'Smart insights', arSmall: 'ملخصات وتوصيات', enSmall: 'Summaries and recommendations' },
  { id: 'sync', icon: 'cloud', ar: 'المزامنة دون اتصال', en: 'Offline synchronization', arSmall: 'طابور محلي آمن', enSmall: 'Secure local queue' },
];

const detailItems = [
  { id: 'analytics', eyebrow: 'PERFORMANCE INTELLIGENCE', titleAr: 'افهم اتجاه الأداء، لا النسبة فقط', titleEn: 'Understand performance direction, not just a percentage', textAr: 'تعرض صفحة الأداء مقارنات يومية وأسبوعية وشهرية، اتجاه الإنتاجية والتركيز، توزيع الوقت، استخدام التطبيقات والمواقع، العلاقة بين إنجاز المهام والنشاط، وتسلسلًا زمنيًا يوضح السياق.', textEn: 'The performance workspace brings together daily, weekly, and monthly comparisons, productivity and focus trends, time distribution, application and website use, task correlations, and a contextual activity timeline.', kind: 'analytics' as const, benefitsAr: ['مقارنات زمنية واضحة', 'مقارنة أعضاء الفريق', 'خرائط حرارة وسياق زمني'], benefitsEn: ['Clear time comparisons', 'Employee comparison', 'Heatmaps and timeline context'] },
  { id: 'activity', eyebrow: 'ACTIVITY SIGNALS', titleAr: 'إشارات عمل ضرورية بحدود شفافة', titleEn: 'Essential work signals with transparent boundaries', textAr: 'يجمع وكيل Windows التطبيقات النشطة، نشاط المواقع حيثما تسمح التقنية، وقت الخمول، مستوى حركة لوحة المفاتيح والماوس، والجلسات. لا يجمع محتوى الكتابة أو كلمات المرور.', textEn: 'The Windows agent captures active applications, website activity where technically possible, idle time, keyboard and mouse activity level, and sessions. It does not capture typed content or passwords.', kind: 'activity' as const, benefitsAr: ['جمع أثناء الجلسة', 'لا تسجيل لمحتوى الكتابة', 'حالة مرئية للموظف'], benefitsEn: ['Session-only collection', 'No typed content capture', 'Visible employee status'] },
  { id: 'tasks', eyebrow: 'WORKFLOW CONTEXT', titleAr: 'ضع إنجاز المهام بجانب واقع يوم العمل', titleEn: 'Place task delivery beside the reality of the workday', textAr: 'تابع المسؤول والأولوية والحالة والتقدم والمواعيد في جدول عملي، ثم استخدمها كسياق لتحليل الأداء بدل تقييم النشاط بمعزل عن النتائج.', textEn: 'Track owner, priority, status, progress, and deadlines in an operational table, then use that information as context for performance instead of judging activity in isolation.', kind: 'tasks' as const, benefitsAr: ['تقدم مرئي', 'إسناد واضح', 'صلة مباشرة بالتحليلات'], benefitsEn: ['Visible progress', 'Clear ownership', 'Direct analytics context'] },
  { id: 'screenshots', eyebrow: 'VISUAL CONTEXT', titleAr: 'سياق بصري فعّال دون هدر التخزين', titleEn: 'Efficient visual context without storage waste', textAr: 'تُلتقط الصور وفق إعداد المؤسسة خلال الجلسة، تُضغط بكفاءة، ويُمنع حفظ الصور المكررة. تظهر اللقطات داخل ملف الموظف لتبقى مرتبطة بالتحليل الصحيح.', textEn: 'Screenshots follow organization settings during sessions, are efficiently compressed, and avoid duplicate storage. They appear inside the employee profile so visual context stays connected to the right analysis.', kind: 'privacy' as const, benefitsAr: ['منع التكرار', 'ضغط مناسب', 'تخزين محلي قابل للاستبدال'], benefitsEn: ['Deduplication', 'Appropriate compression', 'Replaceable local storage'] },
  { id: 'ai', eyebrow: 'AI INSIGHT LAYER', titleAr: 'ملخصات وتوصيات دون قفل تقني', titleEn: 'Summaries and recommendations without technical lock-in', textAr: 'تعمل المعالجة الذكية كوحدة مستقلة عن منطق الأعمال. يمكن ترقية المزود أو النموذج لاحقًا مع بقاء واجهات النظام والتقارير والبيانات الأساسية مستقرة.', textEn: 'AI processing operates as a module separate from business logic. Providers or models can be upgraded later while core interfaces, reports, and data remain stable.', kind: 'ai' as const, benefitsAr: ['عزل نموذج الذكاء', 'سجل تدقيق للمعالجة', 'توصيات قابلة للتفسير'], benefitsEn: ['Isolated model layer', 'Processing audit trail', 'Explainable recommendations'] },
  { id: 'sync', eyebrow: 'RESILIENT SYNCHRONIZATION', titleAr: 'استمر في العمل حتى عندما ينقطع الاتصال', titleEn: 'Keep working even when connectivity does not', textAr: 'يحفظ الوكيل الأحداث محليًا عند فقد الشبكة، يعرض حالة الاتصال والطابور للموظف، ثم يرسلها تلقائيًا عبر REST الآمن عند عودة الخدمة.', textEn: 'The agent stores events locally during network loss, shows connection and queue status to the employee, then automatically sends them over secure REST when service returns.', kind: 'sync' as const, benefitsAr: ['طابور محلي', 'إعادة محاولة تلقائية', 'مزامنة قابلة للتدقيق'], benefitsEn: ['Local queue', 'Automatic retry', 'Auditable synchronization'] },
];

export default function FeaturesPage() {
  const { ar } = useMarketing();
  return <><MarketingPageHero eyebrow="PRODUCT CAPABILITIES" titleAr="كل ما تحتاجه لرؤية العمل بوضوح" titleEn="Everything you need to see work clearly" textAr="من جمع الإشارات على Windows إلى التحليل واتخاذ القرار داخل لوحة المدير—منظومة متماسكة، بوحدات مستقلة وحدود خصوصية واضحة." textEn="From Windows signal collection to analysis and decisions in the manager dashboard—a cohesive system with independent modules and clear privacy boundaries."/>
    <section className="marketing-section compact"><div className="marketing-container"><div className="feature-index">{indexItems.map(item => <Link href={`#${item.id}`} key={item.id}><span><Icon name={item.icon}/></span><div><strong>{ar ? item.ar : item.en}</strong><small>{ar ? item.arSmall : item.enSmall}</small></div><Icon name="arrow" size={13}/></Link>)}</div></div></section>
    <section className="marketing-section tinted"><div className="marketing-container"><DashboardPreview ar={ar}/></div></section>
    {detailItems.map((item, index) => <section id={item.id} className={`marketing-section detailed-feature${index % 2 ? ' tinted' : ''}`} key={item.id}><div className={`marketing-container feature-story${index % 2 ? ' reverse' : ''}`}><div className="story-copy-block"><span className="marketing-eyebrow">{item.eyebrow}</span><h2>{ar ? item.titleAr : item.titleEn}</h2><p>{ar ? item.textAr : item.textEn}</p><div className="feature-benefit-pills">{(ar ? item.benefitsAr : item.benefitsEn).map(benefit => <span key={benefit}><Icon name="check" size={12}/>{benefit}</span>)}</div></div><div className="story-visual-panel">{item.id === 'sync' ? <AgentPreview ar={ar}/> : <FeatureIllustration kind={item.kind}/>}</div></div></section>)}
    <FinalCta/></>;
}
