'use client';

import { Icon, type IconName } from '../../ui/icons';
import { useMarketing } from '../marketing-context';
import { FinalCta, MarketingPageHero, SectionTitle } from '../marketing-page-components';
import { FeatureIllustration } from '../marketing-visuals';

const principles: Array<{ icon: IconName; ar: string; en: string; arText: string; enText: string }> = [
  { icon: 'eye', ar: 'الوضوح قبل التعقيد', en: 'Clarity before complexity', arText: 'نصمم كل شاشة لتجيب عن سؤال عملي، لا لعرض البيانات لمجرد توفرها.', enText: 'Every screen should answer a practical question, not display data merely because it exists.' },
  { icon: 'shield', ar: 'الخصوصية جزء من التصميم', en: 'Privacy by design', arText: 'حدود الجمع والصلاحيات وسجل التدقيق ليست إضافات متأخرة؛ إنها جزء من أساس المنتج.', enText: 'Collection boundaries, permissions, and audit trails are part of the foundation, not late additions.' },
  { icon: 'layers', ar: 'وحدات مستقلة', en: 'Independent modules', arText: 'لوحة المدير والخادم والوكيل تتواصل عبر REST فقط، كي تتطور كل طبقة بأمان.', enText: 'The manager app, backend, and agent communicate only through REST so each layer can evolve safely.' },
  { icon: 'users', ar: 'الإنسان في القرار', en: 'Humans stay in the decision', arText: 'المؤشرات والرؤى تساعد الحوار الإداري ولا تستبدله بحكم آلي على الموظف.', enText: 'Scores and insights support management conversations; they do not replace them with automated judgment.' },
];

export default function AboutPage() {
  const { ar } = useMarketing();
  return <><MarketingPageHero eyebrow="WHY WE EXIST" titleAr="لأن العمل الموزع يحتاج وضوحًا، لا مزيدًا من الضوضاء" titleEn="Distributed work needs clarity—not more noise" textAr="بُنيت Remote Work Intelligence لتربط النشاط بالنتائج في تجربة عادلة ومفهومة، تساعد المدير والموظف على رؤية يوم العمل من الزاوية نفسها." textEn="Remote Work Intelligence connects activity to outcomes through a fair, understandable experience that lets managers and employees see the workday from the same foundation."/>
    <section className="marketing-section"><div className="marketing-container about-manifesto"><div><span className="marketing-eyebrow">OUR POINT OF VIEW</span><h2>{ar ? 'الإنتاجية ليست حركة أكثر. إنها إنجاز أوضح.' : 'Productivity is not more motion. It is clearer progress.'}</h2></div><div><p>{ar ? 'أدوات المتابعة التقليدية تعرض أرقامًا منفصلة: ساعات، لقطات، نقرات، ومهام. لكن المدير يحتاج سياقًا، والموظف يحتاج شفافية. لذلك صممنا المنصة لتجمع الإشارات الضرورية فقط، ثم ترتبها حول النتائج واتجاهات العمل.' : 'Traditional monitoring tools expose isolated numbers: hours, screenshots, clicks, and tasks. Managers need context, while employees need transparency. We designed the platform to collect only necessary signals and organize them around outcomes and work patterns.'}</p><p>{ar ? 'الهدف ليس زيادة الرقابة، بل تقليل التخمين: أين يضيع الوقت؟ متى يحدث التركيز؟ هل ضغط العمل مرتبط بتأخر المهام؟ ومن يحتاج دعمًا قبل أن تتحول الإشارة إلى مشكلة؟' : 'The goal is not more surveillance, but less guessing: where time is lost, when focus happens, whether workload relates to delayed tasks, and who needs support before a signal becomes a problem.'}</p></div></div></section>
    <section className="marketing-section tinted"><div className="marketing-container vision-band"><article><span>{ar ? 'رؤيتنا' : 'OUR VISION'}</span><h2>{ar ? 'بيئة عمل موزعة يمكن فهمها بثقة.' : 'Distributed work that can be understood with confidence.'}</h2><p>{ar ? 'نرى مستقبلًا تكون فيه بيانات العمل مشتركة المعنى، واضحة الحدود، ومفيدة لتحسين النظام بدل استخدامها للحكم السريع على الأفراد.' : 'We envision work data with shared meaning, clear boundaries, and a purpose of improving systems rather than enabling rushed judgments about individuals.'}</p></article><article><span>{ar ? 'مهمتنا' : 'OUR MISSION'}</span><h2>{ar ? 'تحويل إشارات العمل إلى قرارات إنسانية أفضل.' : 'Turn work signals into better human decisions.'}</h2><p>{ar ? 'نمنح الفرق رؤية عملية للوقت والتركيز والإنجاز، مع بنية مستقرة وتجربة ثنائية اللغة وخصوصية مفهومة منذ البداية.' : 'We give teams an operational view of time, focus, and delivery with a stable architecture, bilingual experience, and understandable privacy from day one.'}</p></article></div></section>
    <section className="marketing-section"><div className="marketing-container"><SectionTitle eyebrow="PRODUCT PRINCIPLES" titleAr="مبادئ لا تتغير بتغيّر الشاشة" titleEn="Principles that do not change with the screen" textAr="هذه المبادئ توجه تجربة الموقع العام ولوحة المدير ووكيل الموظف معًا." textEn="These principles guide the public website, manager dashboard, and employee agent together."/><div className="principles-grid">{principles.map(item => <article className="principle-card" key={item.en}><span><Icon name={item.icon}/></span><h3>{ar ? item.ar : item.en}</h3><p>{ar ? item.arText : item.enText}</p></article>)}</div></div></section>
    <section className="marketing-section compact tinted"><div className="marketing-container feature-story"><div className="story-copy-block"><span className="marketing-eyebrow">BUILT TO EVOLVE</span><h2>{ar ? 'هوية موحدة، وحدود تقنية واضحة' : 'One identity, clear technical boundaries'}</h2><p>{ar ? 'يشترك الموقع التسويقي ولوحة المدير والوكيل في اللغة البصرية والخط الذي تختاره المؤسسة، لكن كل تجربة تبقى مستقلة وظيفيًا. هذه الموازنة تجعل المنتج متماسكًا أمام المستخدم وقابلًا للصيانة خلف الكواليس.' : 'The marketing site, manager dashboard, and agent share a visual language and organization-selected typography while remaining functionally independent. That balance keeps the product coherent for users and maintainable behind the scenes.'}</p></div><div className="story-visual-panel"><FeatureIllustration kind="sync"/></div></div></section><FinalCta/></>;
}
