'use client';

import Link from 'next/link';
import { useMarketing } from './marketing-context';
import { MarketingPageHero } from './marketing-page-components';

type Kind = 'privacy' | 'terms' | 'cookies';
type LegalSection = { id: string; titleAr: string; titleEn: string; paragraphsAr: string[]; paragraphsEn: string[]; bulletsAr?: string[]; bulletsEn?: string[] };

const documents: Record<Kind, { eyebrow: string; titleAr: string; titleEn: string; introAr: string; introEn: string; noticeAr: string; noticeEn: string; sections: LegalSection[] }> = {
  privacy: {
    eyebrow: 'PRIVACY POLICY', titleAr: 'سياسة الخصوصية', titleEn: 'Privacy Policy', introAr: 'توضح هذه السياسة كيف تتعامل منصة Remote Work Intelligence مع بيانات الحساب والعمل والنشاط عند استخدام الموقع العام ولوحة المدير ووكيل Windows.', introEn: 'This policy explains how Remote Work Intelligence handles account, work, and activity data across the public website, manager dashboard, and Windows agent.', noticeAr: 'تنبيه مهم: تتحمل المؤسسة المشتركة مسؤولية إبلاغ موظفيها والحصول على الموافقات اللازمة وتحديد أساس قانوني مناسب قبل تفعيل جمع النشاط.', noticeEn: 'Important: the subscribing organization is responsible for informing employees, obtaining required approvals, and establishing an appropriate legal basis before activity collection is enabled.',
    sections: [
      { id: 'scope', titleAr: '1. النطاق والأدوار', titleEn: '1. Scope and roles', paragraphsAr: ['تنطبق هذه السياسة على تجربة المنتج الحالية. تكون المؤسسة عادةً مسؤولة عن تحديد أغراض ومدة جمع بيانات موظفيها، بينما تعالج المنصة البيانات لتقديم الخدمة وفق إعدادات المؤسسة.', 'لا تنطبق هذه السياسة على مواقع أو خدمات خارجية قد ترتبط بالمنصة مستقبلًا؛ ستخضع تلك الخدمات لسياساتها الخاصة.'], paragraphsEn: ['This policy applies to the current product experience. The organization generally determines the purposes and duration of employee data collection, while the platform processes data to deliver the service under organization settings.', 'This policy does not cover external services that may be connected in the future; those services will be governed by their own policies.'] },
      { id: 'data', titleAr: '2. البيانات التي تتم معالجتها', titleEn: '2. Data we process', paragraphsAr: ['تعتمد البيانات الفعلية على إعدادات المؤسسة والقدرات التقنية المتاحة. لا يحاول تطبيق الويب جمع نشاط سطح المكتب.'], paragraphsEn: ['The actual data depends on organization settings and available technical capabilities. The web application does not attempt to collect desktop activity.'], bulletsAr: ['بيانات الحساب: الاسم، بريد العمل، الدور، حالة الحساب، وأحداث المصادقة.', 'بيانات الجلسة: وقت البدء والانتهاء، الوقت النشط والخامل، وحالة المزامنة.', 'إشارات النشاط: التطبيق النشط، نشاط المواقع حيثما تسمح التقنية، ومستوى نشاط لوحة المفاتيح والماوس.', 'لقطات الشاشة التي تلتقط خلال جلسة العمل وفق الإعدادات.', 'بيانات المهام والتقدم والملاحظات والإشعارات.', 'نتائج التحليلات والرؤى الذكية وسجلات المعالجة والتدقيق.'], bulletsEn: ['Account data: name, work email, role, account status, and authentication events.', 'Session data: start and end time, active and idle time, and synchronization status.', 'Activity signals: active application, website activity where technically possible, and keyboard and mouse activity levels.', 'Screenshots captured during work sessions under configured settings.', 'Task, progress, note, and notification data.', 'Analytics, smart insight outputs, processing records, and audit logs.'] },
      { id: 'not-collected', titleAr: '3. ما لا يتم جمعه', titleEn: '3. What is not collected', paragraphsAr: ['لا يسجل النظام المفاتيح التي يضغطها الموظف أو النص المكتوب أو كلمات المرور. قياس لوحة المفاتيح هو مستوى نشاط عددي فقط. لا يعمل تطبيق المدير كمجمع لنشاط سطح المكتب، ولا يصل أي مكون إلى قاعدة بيانات مكون آخر مباشرةً.'], paragraphsEn: ['The system does not record individual keystrokes, typed text, or passwords. Keyboard measurement is an activity level only. The manager application does not act as a desktop collector, and no component directly accesses another component’s database.'] },
      { id: 'purpose', titleAr: '4. أغراض الاستخدام', titleEn: '4. Purposes of use', paragraphsAr: ['تُستخدم البيانات لتشغيل المصادقة والجلسات، مزامنة نشاط العمل، عرض التحليلات والتقارير، إدارة المهام، اكتشاف المشكلات التشغيلية، إنشاء الرؤى الذكية، حماية الخدمة، وتسجيل العمليات المهمة.'], paragraphsEn: ['Data is used to operate authentication and sessions, synchronize work activity, present analytics and reports, manage tasks, identify operational issues, generate smart insights, protect the service, and record important operations.'] },
      { id: 'storage', titleAr: '5. التخزين والاحتفاظ', titleEn: '5. Storage and retention', paragraphsAr: ['عند انقطاع الاتصال يحتفظ وكيل Windows بطابور محلي للبيانات إلى أن تنجح المزامنة. تُضغط لقطات الشاشة ويُمنع حفظ الصور المتطابقة قدر الإمكان. طبقة التخزين قابلة للاستبدال بين التخزين المحلي والسحابي مستقبلًا.', 'تحدد المؤسسة مدد الاحتفاظ المناسبة وفق احتياجها والتزاماتها. ينبغي حذف البيانات أو إخفاء هويتها عندما تنتهي الحاجة المشروعة إليها.'], paragraphsEn: ['During connectivity loss, the Windows agent maintains a local data queue until synchronization succeeds. Screenshots are compressed and duplicate images are avoided where possible. The storage layer can be replaced between local and future cloud storage.', 'The organization determines appropriate retention periods according to its needs and obligations. Data should be deleted or de-identified when its legitimate purpose ends.'] },
      { id: 'security', titleAr: '6. الأمان والوصول', titleEn: '6. Security and access', paragraphsAr: ['تتواصل المكونات عبر REST APIs آمنة فقط. تُطبق المصادقة والوصول حسب الدور وتُسجل العمليات المهمة في سجل تدقيق، بما يشمل أحداث الدخول والإدارة والمهام والمعالجة الذكية ومزامنة النشاط.', 'لا توجد وسيلة تقنية تضمن أمانًا مطلقًا. يجب على المؤسسات حماية حساباتها وأجهزتها وتطبيق تحديثات الأمان والإبلاغ عن أي نشاط غير مصرح.'], paragraphsEn: ['Components communicate only through secure REST APIs. Authentication, role-based access, and audit logging cover important operations including sign-in, administration, tasks, AI processing, and activity synchronization.', 'No technical measure guarantees absolute security. Organizations should protect accounts and devices, apply security updates, and report unauthorized activity.'] },
      { id: 'rights', titleAr: '7. الشفافية وحقوق الأفراد', titleEn: '7. Transparency and individual rights', paragraphsAr: ['ينبغي للمؤسسة تزويد الموظفين بإشعار واضح يشرح البيانات المفعلة والغرض ومدة الاحتفاظ وجهات الوصول. قد تشمل الحقوق—بحسب القانون المطبق—الوصول والتصحيح والحذف والتقييد والاعتراض.', 'يمكن للموظف البدء بالتواصل مع مسؤول مؤسسته لأن المؤسسة تدير الحساب وإعدادات الجمع. ويمكن للمؤسسة التواصل معنا عبر صفحة التواصل لطلبات الخدمة المرتبطة بهذه الحقوق.'], paragraphsEn: ['Organizations should provide employees with a clear notice describing enabled data, purpose, retention, and who can access it. Depending on applicable law, rights may include access, correction, deletion, restriction, and objection.', 'Employees may begin by contacting their organization administrator because the organization manages the account and collection settings. The organization can contact us through the contact page for service-related assistance.'] },
      { id: 'changes', titleAr: '8. التحديثات والتواصل', titleEn: '8. Updates and contact', paragraphsAr: ['قد تُحدث هذه السياسة عندما تتغير الخدمة أو المتطلبات. سيظهر تاريخ السريان أعلى الصفحة، ويُنصح بمراجعة التغييرات قبل استمرار الاستخدام.', 'للاستفسارات المتعلقة بالخصوصية استخدم صفحة التواصل وحدد أن الطلب يتعلق بالخصوصية.'], paragraphsEn: ['This policy may be updated as the service or requirements change. The effective date appears above, and changes should be reviewed before continued use.', 'For privacy questions, use the contact page and identify the request as privacy-related.'] },
    ],
  },
  terms: {
    eyebrow: 'TERMS OF SERVICE', titleAr: 'شروط الخدمة', titleEn: 'Terms of Service', introAr: 'تنظم هذه الشروط الوصول إلى Remote Work Intelligence واستخدام الموقع العام ولوحة المدير ووكيل Windows.', introEn: 'These terms govern access to Remote Work Intelligence, including the public website, manager dashboard, and Windows agent.', noticeAr: 'باستخدام الخدمة، تقر بأنك مخول بقبول هذه الشروط عن نفسك أو عن المؤسسة التي تمثلها.', noticeEn: 'By using the service, you confirm that you are authorized to accept these terms for yourself or the organization you represent.',
    sections: [
      { id: 'service', titleAr: '1. الخدمة والنطاق', titleEn: '1. Service and scope', paragraphsAr: ['توفر المنصة أدوات لإدارة فرق العمل وتحليل الإنتاجية وإدارة المهام ومزامنة نشاط وكيل الموظف وإنشاء التقارير والرؤى. قد تتطور الميزات بمرور الوقت، وستُوضح الميزات غير المفعلة بأنها مستقبلية أو مخطط لها.'], paragraphsEn: ['The platform provides team management, productivity analytics, task management, employee agent synchronization, reporting, and insight tools. Features may evolve, and unavailable capabilities are identified as future-ready or planned.'] },
      { id: 'accounts', titleAr: '2. الحسابات والصلاحيات', titleEn: '2. Accounts and permissions', paragraphsAr: ['يجب تقديم معلومات صحيحة، حماية بيانات الدخول، وعدم مشاركة الحساب بوسيلة تتجاوز الصلاحيات الممنوحة. تتحمل المؤسسة مسؤولية تعيين الأدوار وإلغاء الوصول عند انتهاء الحاجة.', 'قد نقيّد الوصول عند الاشتباه في إساءة الاستخدام أو خرق الأمان أو مخالفة هذه الشروط.'], paragraphsEn: ['You must provide accurate information, protect credentials, and avoid sharing an account beyond granted permissions. The organization is responsible for assigning roles and removing access when it is no longer needed.', 'Access may be restricted when misuse, a security breach, or violation of these terms is suspected.'] },
      { id: 'lawful-use', titleAr: '3. الاستخدام المشروع ومراقبة الموظفين', titleEn: '3. Lawful use and employee monitoring', paragraphsAr: ['تتحمل المؤسسة وحدها مسؤولية التأكد من مشروعية جمع نشاط الموظف في مواقع العمل ذات الصلة، وتقديم الإشعارات والحصول على الموافقات المطلوبة واحترام حقوق الموظفين وسياسات العمل.', 'يُحظر استخدام الخدمة للمراقبة السرية غير القانونية أو التمييز أو المضايقة أو جمع بيانات خارج الغرض المعلن.'], paragraphsEn: ['The organization is solely responsible for ensuring employee activity collection is lawful in relevant workplaces, providing notices, obtaining required approvals, and respecting employee rights and workplace policies.', 'The service must not be used for unlawful secret surveillance, discrimination, harassment, or collection beyond the stated purpose.'] },
      { id: 'acceptable', titleAr: '4. الاستخدام المقبول', titleEn: '4. Acceptable use', paragraphsAr: ['يُحظر محاولة اختراق الخدمة أو تجاوز الصلاحيات أو تعطيلها أو رفع محتوى ضار أو استخدام البيانات لاتخاذ قرارات محظورة قانونيًا. لا يجوز تفكيك حدود المكونات أو الوصول المباشر إلى قواعد البيانات خارج الوسائل المصرح بها.'], paragraphsEn: ['You must not attempt to breach the service, bypass authorization, disrupt availability, upload harmful content, or use data for legally prohibited decisions. Component boundaries must not be bypassed and databases must not be accessed outside authorized means.'] },
      { id: 'customer-data', titleAr: '5. بيانات المؤسسة', titleEn: '5. Organization data', paragraphsAr: ['تحتفظ المؤسسة بحقوقها في بياناتها. تمنح المؤسسة الصلاحية اللازمة لمعالجة البيانات لتشغيل الخدمة وتأمينها ودعمها وفق الإعدادات المتفق عليها.', 'تتحمل المؤسسة مسؤولية دقة البيانات ومشروعية رفعها وتحديد مدد الاحتفاظ والنسخ المطلوبة لها.'], paragraphsEn: ['The organization retains its rights in its data and grants the permissions needed to process that data to operate, secure, and support the service under agreed settings.', 'The organization is responsible for data accuracy, lawful submission, retention periods, and any required copies.'] },
      { id: 'ai', titleAr: '6. الرؤى الذكية', titleEn: '6. Smart insights', paragraphsAr: ['المخرجات الذكية تقديرية وقد تكون غير مكتملة أو غير دقيقة. يجب مراجعتها بشريًا وعدم استخدامها منفردة في قرارات التوظيف أو العقوبات أو الحقوق القانونية. يبقى المدير مسؤولًا عن القرار والسياق.'], paragraphsEn: ['Smart outputs are probabilistic and may be incomplete or inaccurate. They require human review and must not be used alone for employment, disciplinary, or legal-right decisions. Managers remain responsible for decisions and context.'] },
      { id: 'availability', titleAr: '7. التوفر والتحديثات', titleEn: '7. Availability and updates', paragraphsAr: ['نسعى لتوفير خدمة مستقرة، لكن قد تحدث فترات صيانة أو أعطال أو قيود مرتبطة بالنظام أو الشبكة. تساعد آلية الطابور المحلي في الوكيل على تحمل الانقطاع المؤقت لكنها لا تلغي كل مخاطر فقد البيانات.', 'قد تتطلب تحديثات وكيل Windows إعادة تشغيل أو صلاحية تثبيت مناسبة في الجهاز.'], paragraphsEn: ['We aim for a stable service, but maintenance, outages, operating-system limits, or network issues may occur. The agent’s local queue helps tolerate temporary disconnection but cannot eliminate every risk of data loss.', 'Windows agent updates may require restart or appropriate installation permissions.'] },
      { id: 'liability', titleAr: '8. الضمانات والمسؤولية', titleEn: '8. Warranties and liability', paragraphsAr: ['تقدم الخدمة وفق النطاق المتفق عليه ودون ضمان نتائج إنتاجية محددة. إلى الحد الذي يسمح به القانون، لا نتحمل أضرارًا غير مباشرة ناتجة عن إساءة استخدام البيانات أو الاعتماد المنفرد على المؤشرات.', 'تُحدد الشروط التجارية النهائية وحدود المسؤولية في اتفاقية الاشتراك عند تفعيل الخدمات المدفوعة.'], paragraphsEn: ['The service is provided within the agreed scope without guaranteeing specific productivity outcomes. To the extent permitted by law, we are not responsible for indirect harm caused by misuse of data or sole reliance on metrics.', 'Final commercial terms and liability limits will be defined in the subscription agreement when paid services are activated.'] },
      { id: 'termination', titleAr: '9. الإنهاء والتواصل', titleEn: '9. Termination and contact', paragraphsAr: ['يمكن إنهاء الاستخدام وفق اتفاقية الخدمة. عند الإنهاء ينبغي إلغاء وصول المستخدمين ومعالجة تصدير البيانات أو حذفها وفق مدة متفق عليها والالتزامات النظامية.', 'للاستفسارات القانونية أو التعاقدية استخدم صفحة التواصل.'], paragraphsEn: ['Use may be terminated under the service agreement. On termination, user access should be removed and data export or deletion handled under an agreed period and applicable obligations.', 'For legal or contract questions, use the contact page.'] },
    ],
  },
  cookies: {
    eyebrow: 'COOKIES POLICY', titleAr: 'سياسة ملفات الارتباط', titleEn: 'Cookies Policy', introAr: 'توضح هذه السياسة استخدام ملفات الارتباط والتخزين المحلي في الموقع العام ولوحة المدير.', introEn: 'This policy explains the use of cookies and local storage across the public website and manager dashboard.', noticeAr: 'تستخدم النسخة الحالية تقنيات ضرورية للجلسة وتفضيلات اللغة والمظهر. لا نستخدم ملفات إعلانات أو تتبع سلوكي تسويقي من أطراف خارجية.', noticeEn: 'The current version uses technologies necessary for sessions and language/theme preferences. We do not use third-party advertising or behavioral marketing trackers.',
    sections: [
      { id: 'definitions', titleAr: '1. ما هي ملفات الارتباط؟', titleEn: '1. What are cookies?', paragraphsAr: ['ملفات الارتباط بيانات صغيرة يحفظها المتصفح لدعم تسجيل الدخول والوظائف الأساسية. التخزين المحلي مساحة في المتصفح تُستخدم لحفظ تفضيلات غير حساسة مثل اللغة والثيم والخط.'], paragraphsEn: ['Cookies are small pieces of data stored by the browser to support sign-in and essential functionality. Local storage is browser space used for non-sensitive preferences such as language, theme, and typography.'] },
      { id: 'essential', titleAr: '2. الملفات الضرورية', titleEn: '2. Essential cookies', paragraphsAr: ['تحتاج المصادقة إلى ملفات جلسة آمنة لتحديد المستخدم المصرح وتجديد الوصول. لا يمكن تعطيل هذه الملفات مع استمرار تسجيل الدخول لأنها ضرورية لتقديم لوحة محمية.'], paragraphsEn: ['Authentication requires secure session cookies to identify authorized users and renew access. These cookies cannot be disabled while remaining signed in because they are necessary for a protected dashboard.'] },
      { id: 'preferences', titleAr: '3. تفضيلات الواجهة', titleEn: '3. Interface preferences', paragraphsAr: ['تُحفظ اللغة العربية أو الإنجليزية، اتجاه الواجهة، والثيم الفاتح أو الداكن محليًا على الجهاز. وقد يُطبق الخط الذي يختاره مسؤول المؤسسة عبر إعدادات النظام.'], paragraphsEn: ['Arabic or English language, interface direction, and light or dark theme are saved locally on the device. The organization-selected font may be applied through system settings.'] },
      { id: 'analytics', titleAr: '4. تحليلات الموقع العام', titleEn: '4. Public website analytics', paragraphsAr: ['لا تتضمن النسخة الحالية أداة تحليلات تسويقية خارجية أو ملفات استهداف إعلاني. إذا أضيفت أداة مستقبلًا، ستُحدّث هذه السياسة وتُطبق آلية موافقة مناسبة قبل تشغيل الملفات غير الضرورية حيث يلزم.'], paragraphsEn: ['The current version does not include external marketing analytics or advertising-targeting cookies. If such a tool is added later, this policy will be updated and appropriate consent controls applied before non-essential cookies operate where required.'] },
      { id: 'agent', titleAr: '5. وكيل Windows', titleEn: '5. Windows agent', paragraphsAr: ['لا يعتمد وكيل سطح المكتب على ملفات ارتباط المتصفح لجمع النشاط. يستخدم تخزينًا محليًا خاصًا بالتطبيق لحفظ الجلسة والطابور المؤقت عند انقطاع الاتصال وفق تصميمه الأمني.'], paragraphsEn: ['The desktop agent does not rely on browser cookies for activity collection. It uses application-specific local storage for its session and temporary offline queue under its security design.'] },
      { id: 'control', titleAr: '6. التحكم والحذف', titleEn: '6. Control and deletion', paragraphsAr: ['يمكنك حذف بيانات الموقع من إعدادات المتصفح. سيؤدي حذف ملفات الجلسة إلى تسجيل خروجك، وقد يؤدي حذف التخزين المحلي إلى إعادة اللغة والثيم إلى الوضع الافتراضي.', 'يمكن تغيير اللغة والثيم مباشرة من رأس الموقع دون حذف البيانات.'], paragraphsEn: ['You can clear site data through browser settings. Removing session cookies signs you out, while clearing local storage may reset language and theme preferences.', 'Language and theme can be changed directly from the website header without clearing data.'] },
      { id: 'changes', titleAr: '7. تحديث السياسة', titleEn: '7. Policy updates', paragraphsAr: ['سنحدث هذه الصفحة عند إضافة تقنية تخزين جديدة أو تغيير الغرض من الاستخدام. يوضح تاريخ السريان النسخة المعمول بها. للاستفسار استخدم صفحة التواصل.'], paragraphsEn: ['This page will be updated if a new storage technology is introduced or a purpose changes. The effective date identifies the current version. Use the contact page for questions.'] },
    ],
  },
};

export default function LegalDocument({ kind }: { kind: Kind }) {
  const { ar } = useMarketing();
  const document = documents[kind];
  return <><MarketingPageHero eyebrow={document.eyebrow} titleAr={document.titleAr} titleEn={document.titleEn} textAr={document.introAr} textEn={document.introEn} actions={false}/><div className="legal-meta"><span>{ar ? 'تاريخ السريان: 5 أغسطس 2026' : 'Effective: August 5, 2026'}</span><span>·</span><span>{ar ? 'الإصدار 1.0' : 'Version 1.0'}</span></div><section className="marketing-section compact"><div className="marketing-container legal-layout"><aside className="legal-index"><strong>{ar ? 'المحتويات' : 'CONTENTS'}</strong>{document.sections.map(section => <a href={`#${section.id}`} key={section.id}>{ar ? section.titleAr : section.titleEn}</a>)}</aside><article className="legal-content"><p>{ar ? document.noticeAr : document.noticeEn}</p>{document.sections.map(section => <section id={section.id} key={section.id}><h2>{ar ? section.titleAr : section.titleEn}</h2>{(ar ? section.paragraphsAr : section.paragraphsEn).map(paragraph => <p key={paragraph}>{paragraph}</p>)}{(ar ? section.bulletsAr : section.bulletsEn) && <ul>{(ar ? section.bulletsAr : section.bulletsEn)?.map(bullet => <li key={bullet}>{bullet}</li>)}</ul>}</section>)}<p>{ar ? 'تحتاج إلى توضيح؟ ' : 'Need clarification? '}<Link href="/contact">{ar ? 'تواصل معنا.' : 'Contact us.'}</Link></p></article></div></section></>;
}
